package model

import "time"

const (
	// POWChallengeStatusActive marks one currently solvable challenge row.
	POWChallengeStatusActive = "active"

	// POWChallengeStatusSuperseded marks one older challenge that was replaced
	// by a newly generated challenge for the same user.
	POWChallengeStatusSuperseded = "superseded"

	// POWChallengeStatusClaimed marks one challenge that was solved, verified,
	// and already turned into a real reward.
	POWChallengeStatusClaimed = "claimed"

	// POWBenefitEmailCatchAllRemainingCount is the first user-visible PoW reward
	// type. Solving the puzzle grants extra catch-all mail delivery count.
	POWBenefitEmailCatchAllRemainingCount = "email_catch_all_remaining_count"
)

// POWChallenge stores one user-bound proof-of-work puzzle generated by the
// backend. Only one challenge should remain active per user at any time, while
// older rows stay auditable after they are superseded or claimed.
type POWChallenge struct {
	ID                int64      `json:"id"`
	UserID            int64      `json:"user_id"`
	BenefitKey        string     `json:"benefit_key"`
	ResourceKey       string     `json:"resource_key"`
	Scope             string     `json:"scope"`
	Difficulty        int        `json:"difficulty"`
	BaseReward        int        `json:"base_reward"`
	RewardQuantity    int        `json:"reward_quantity"`
	RewardUnit        string     `json:"reward_unit"`
	ChallengeToken    string     `json:"challenge_token"`
	SaltHex           string     `json:"salt_hex"`
	Argon2Variant     string     `json:"argon2_variant"`
	Argon2MemoryKiB   uint32     `json:"argon2_memory_kib"`
	Argon2Iterations  uint32     `json:"argon2_iterations"`
	Argon2Parallelism uint8      `json:"argon2_parallelism"`
	Argon2HashLength  uint32     `json:"argon2_hash_length"`
	Status            string     `json:"status"`
	SolutionNonce     string     `json:"solution_nonce,omitempty"`
	SolutionHashHex   string     `json:"solution_hash_hex,omitempty"`
	ClaimedAt         *time.Time `json:"claimed_at,omitempty"`
	SupersededAt      *time.Time `json:"superseded_at,omitempty"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}
