package service

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"net/url"
	"strconv"
	"strings"
	"time"

	"linuxdospace/backend/internal/config"
	"linuxdospace/backend/internal/linuxdocredit"
	"linuxdospace/backend/internal/model"
	"linuxdospace/backend/internal/security"
	"linuxdospace/backend/internal/storage"
)

const (
	// PaymentProductEmailCatchAllSubscription is the stable product key used to
	// sell catch-all subscription days through Linux Do Credit.
	PaymentProductEmailCatchAllSubscription = "email_catch_all_subscription"

	// PaymentProductEmailCatchAllQuota is the stable product key used to sell
	// prepaid catch-all delivery count in fixed-size batches.
	PaymentProductEmailCatchAllQuota = "email_catch_all_quota"

	// PaymentProductTest is a low-cost gateway smoke-test product that verifies
	// the full create-query-notify flow without changing real user features.
	PaymentProductTest = "payment_test"

	// QuantitySourceLinuxDOCredit marks immutable ledger rows generated by a
	// successful Linux Do Credit purchase.
	QuantitySourceLinuxDOCredit = "linuxdo_credit"

	// QuantityResourcePaymentTestCounts stores how many successful payment-test
	// purchases a user has completed.
	QuantityResourcePaymentTestCounts = "payment_test_count"

	maxPaymentOrderUnits = 100000
)

// PaymentService owns Linux Do Credit product configuration, order creation,
// asynchronous callback verification, and idempotent entitlement application.
type PaymentService struct {
	cfg    config.Config
	db     Store
	cf     CloudflareClient
	credit LinuxDOCreditClient
}

// CreatePaymentOrderRequest describes one authenticated user's checkout
// request against a configured LDC product.
type CreatePaymentOrderRequest struct {
	ProductKey string `json:"product_key"`
	Units      int64  `json:"units"`
}

// UpdatePaymentProductRequest describes the administrator-editable subset of
// one purchasable LDC product row.
type UpdatePaymentProductRequest struct {
	Enabled       *bool  `json:"enabled,omitempty"`
	UnitPrice     string `json:"unit_price,omitempty"`
	GrantQuantity *int64 `json:"grant_quantity,omitempty"`
}

// NewPaymentService constructs the LDC purchase service.
func NewPaymentService(cfg config.Config, db Store, cf CloudflareClient, credit LinuxDOCreditClient) *PaymentService {
	return &PaymentService{
		cfg:    cfg,
		db:     db,
		cf:     cf,
		credit: credit,
	}
}

// ListPublicProducts returns all enabled LDC products in display order.
func (s *PaymentService) ListPublicProducts(ctx context.Context) ([]model.PaymentProduct, error) {
	items, err := s.db.ListPaymentProducts(ctx, false)
	if err != nil {
		return nil, InternalError("failed to list payment products", err)
	}
	filtered := make([]model.PaymentProduct, 0, len(items))
	for _, item := range items {
		if item.Key == PaymentProductDomainAllocationPurchase || item.EffectType == model.PaymentEffectDomainAllocationPurchase {
			continue
		}
		filtered = append(filtered, item)
	}
	return filtered, nil
}

// ListPaymentProducts returns the full administrator-facing product set,
// including disabled items that should stay editable in the console.
func (s *PaymentService) ListPaymentProducts(ctx context.Context) ([]model.PaymentProduct, error) {
	items, err := s.db.ListPaymentProducts(ctx, true)
	if err != nil {
		return nil, InternalError("failed to list payment products", err)
	}
	return items, nil
}

// UpdatePaymentProduct applies one administrator-authored pricing or grant
// change to a stable product definition.
func (s *PaymentService) UpdatePaymentProduct(ctx context.Context, actor model.User, productKey string, request UpdatePaymentProductRequest) (model.PaymentProduct, error) {
	item, err := s.db.GetPaymentProduct(ctx, strings.TrimSpace(productKey))
	if err != nil {
		if storage.IsNotFound(err) {
			return model.PaymentProduct{}, NotFoundError("payment product not found")
		}
		return model.PaymentProduct{}, InternalError("failed to load payment product", err)
	}

	if request.Enabled != nil {
		item.Enabled = *request.Enabled
	}
	if strings.TrimSpace(request.UnitPrice) != "" {
		unitPriceCents, parseErr := parseMoneyToCents(request.UnitPrice)
		if parseErr != nil {
			return model.PaymentProduct{}, ValidationError(parseErr.Error())
		}
		if unitPriceCents <= 0 {
			return model.PaymentProduct{}, ValidationError("unit_price must be greater than 0")
		}
		item.UnitPriceCents = unitPriceCents
	}
	if request.GrantQuantity != nil {
		if *request.GrantQuantity <= 0 {
			return model.PaymentProduct{}, ValidationError("grant_quantity must be greater than 0")
		}
		item.GrantQuantity = *request.GrantQuantity
	}

	updated, err := s.db.UpsertPaymentProduct(ctx, storage.UpsertPaymentProductInput{
		Key:            item.Key,
		DisplayName:    item.DisplayName,
		Description:    item.Description,
		Enabled:        item.Enabled,
		UnitPriceCents: item.UnitPriceCents,
		GrantQuantity:  item.GrantQuantity,
		GrantUnit:      item.GrantUnit,
		EffectType:     item.EffectType,
		SortOrder:      item.SortOrder,
	})
	if err != nil {
		return model.PaymentProduct{}, InternalError("failed to update payment product", err)
	}

	metadata, _ := json.Marshal(map[string]any{
		"product_key":      updated.Key,
		"enabled":          updated.Enabled,
		"unit_price_cents": updated.UnitPriceCents,
		"grant_quantity":   updated.GrantQuantity,
		"grant_unit":       updated.GrantUnit,
		"effect_type":      updated.EffectType,
	})
	logAuditWriteFailure("admin.payment_product.update", s.db.WriteAuditLog(ctx, storage.AuditLogInput{
		ActorUserID:  &actor.ID,
		Action:       "admin.payment_product.update",
		ResourceType: "payment_product",
		ResourceID:   updated.Key,
		MetadataJSON: string(metadata),
	}))

	return updated, nil
}

// CreateOrder reserves one local LDC order, requests the gateway checkout URL,
// and returns the now-payable order to the frontend.
func (s *PaymentService) CreateOrder(ctx context.Context, user model.User, request CreatePaymentOrderRequest) (model.PaymentOrder, error) {
	if s.credit == nil || !s.credit.Configured() || !s.cfg.LinuxDOCreditConfigured() {
		return model.PaymentOrder{}, UnavailableError("linux.do credit payment is not configured", nil)
	}

	product, units, err := s.validateOrderCreation(ctx, user, request)
	if err != nil {
		return model.PaymentOrder{}, err
	}

	grantedTotal, err := multiplyInt64Checked(product.GrantQuantity, units)
	if err != nil {
		return model.PaymentOrder{}, ValidationError("requested units are too large")
	}
	totalPriceCents, err := multiplyInt64Checked(product.UnitPriceCents, units)
	if err != nil {
		return model.PaymentOrder{}, ValidationError("requested units are too large")
	}

	outTradeNo, err := generateOutTradeNo()
	if err != nil {
		return model.PaymentOrder{}, InternalError("failed to generate payment order number", err)
	}

	title := buildPaymentOrderTitle(product, units)
	order, err := s.db.CreatePaymentOrder(ctx, storage.CreatePaymentOrderInput{
		UserID:          user.ID,
		ProductKey:      product.Key,
		ProductName:     product.DisplayName,
		Title:           title,
		GatewayType:     model.PaymentGatewayLinuxDOCredit,
		OutTradeNo:      outTradeNo,
		Status:          model.PaymentOrderStatusCreated,
		Units:           units,
		GrantQuantity:   product.GrantQuantity,
		GrantedTotal:    grantedTotal,
		GrantUnit:       product.GrantUnit,
		UnitPriceCents:  product.UnitPriceCents,
		TotalPriceCents: totalPriceCents,
		EffectType:      product.EffectType,
		PaymentURL:      "",
	})
	if err != nil {
		return model.PaymentOrder{}, InternalError("failed to create local payment order", err)
	}

	logAuditWriteFailure("payment.order.create", s.db.WriteAuditLog(ctx, storage.AuditLogInput{
		ActorUserID:  &user.ID,
		Action:       "payment.order.create",
		ResourceType: "payment_order",
		ResourceID:   order.OutTradeNo,
		MetadataJSON: fmt.Sprintf(`{"product_key":"%s","units":%d,"total_price_cents":%d}`, product.Key, units, totalPriceCents),
	}))

	submitResult, submitErr := s.credit.SubmitOrder(ctx, linuxdocredit.SubmitOrderRequest{
		OutTradeNo: outTradeNo,
		Name:       title,
		Money:      formatMoneyFromCents(totalPriceCents),
	})
	if submitErr != nil {
		now := time.Now().UTC()
		_, updateErr := s.db.UpdatePaymentOrderGatewayState(ctx, storage.UpdatePaymentOrderGatewayStateInput{
			OutTradeNo:    outTradeNo,
			Status:        model.PaymentOrderStatusFailed,
			LastCheckedAt: &now,
		})
		logPostMutationFailure("payment.order.mark_failed", updateErr)
		return model.PaymentOrder{}, UnavailableError("failed to create linux.do credit checkout", submitErr)
	}

	order, err = s.db.UpdatePaymentOrderGatewayState(ctx, storage.UpdatePaymentOrderGatewayStateInput{
		OutTradeNo: outTradeNo,
		Status:     model.PaymentOrderStatusPending,
		PaymentURL: submitResult.PaymentURL,
	})
	if err != nil {
		return model.PaymentOrder{}, InternalError("failed to persist linux.do credit checkout url", err)
	}

	logAuditWriteFailure("payment.order.checkout_ready", s.db.WriteAuditLog(ctx, storage.AuditLogInput{
		ActorUserID:  &user.ID,
		Action:       "payment.order.checkout_ready",
		ResourceType: "payment_order",
		ResourceID:   order.OutTradeNo,
		MetadataJSON: fmt.Sprintf(`{"product_key":"%s","status":"%s"}`, product.Key, order.Status),
	}))

	return order, nil
}

// ListMyOrders returns the authenticated user's recent LDC order history.
func (s *PaymentService) ListMyOrders(ctx context.Context, user model.User) ([]model.PaymentOrder, error) {
	items, err := s.db.ListPaymentOrdersByUser(ctx, user.ID, 50)
	if err != nil {
		return nil, InternalError("failed to list payment orders", err)
	}
	return items, nil
}

// ListOrdersForAdmin returns recent Linux Do Credit orders across all users so
// the administrator console can inspect payment flow health and audit history.
func (s *PaymentService) ListOrdersForAdmin(ctx context.Context) ([]model.PaymentOrder, error) {
	items, err := s.db.ListPaymentOrders(ctx, 200)
	if err != nil {
		return nil, InternalError("failed to list payment orders", err)
	}
	return items, nil
}

// GetMyOrder loads one specific order without mutating its current gateway
// state. Use RefreshMyOrder when the caller explicitly wants reconciliation.
func (s *PaymentService) GetMyOrder(ctx context.Context, user model.User, outTradeNo string) (model.PaymentOrder, error) {
	order, err := s.db.GetPaymentOrderByOutTradeNo(ctx, strings.TrimSpace(outTradeNo))
	if err != nil {
		if storage.IsNotFound(err) {
			return model.PaymentOrder{}, NotFoundError("payment order not found")
		}
		return model.PaymentOrder{}, InternalError("failed to load payment order", err)
	}
	if order.UserID != user.ID {
		return model.PaymentOrder{}, NotFoundError("payment order not found")
	}
	return order, nil
}

// RefreshMyOrder explicitly reconciles one current user's order against the
// upstream gateway and applies entitlements when needed.
func (s *PaymentService) RefreshMyOrder(ctx context.Context, user model.User, outTradeNo string) (model.PaymentOrder, error) {
	order, err := s.GetMyOrder(ctx, user, outTradeNo)
	if err != nil {
		return model.PaymentOrder{}, err
	}
	order, err = s.syncAndApplyOrder(ctx, order)
	if err != nil {
		return model.PaymentOrder{}, err
	}
	return order, nil
}

// GetOrderForAdmin loads one specific order for the administrator console
// without mutating its current gateway state.
func (s *PaymentService) GetOrderForAdmin(ctx context.Context, outTradeNo string) (model.PaymentOrder, error) {
	order, err := s.db.GetPaymentOrderByOutTradeNo(ctx, strings.TrimSpace(outTradeNo))
	if err != nil {
		if storage.IsNotFound(err) {
			return model.PaymentOrder{}, NotFoundError("payment order not found")
		}
		return model.PaymentOrder{}, InternalError("failed to load payment order", err)
	}
	return order, nil
}

// RefreshOrderForAdmin explicitly reconciles one order against the upstream
// gateway for the administrator console.
func (s *PaymentService) RefreshOrderForAdmin(ctx context.Context, outTradeNo string) (model.PaymentOrder, error) {
	order, err := s.GetOrderForAdmin(ctx, outTradeNo)
	if err != nil {
		return model.PaymentOrder{}, err
	}
	order, err = s.syncAndApplyOrder(ctx, order)
	if err != nil {
		return model.PaymentOrder{}, err
	}
	return order, nil
}

// HandleGatewayNotification verifies and applies one asynchronous Linux Do
// Credit success callback.
func (s *PaymentService) HandleGatewayNotification(ctx context.Context, values url.Values) (model.PaymentOrder, bool, error) {
	if s.credit == nil || !s.credit.Configured() || !s.cfg.LinuxDOCreditConfigured() {
		return model.PaymentOrder{}, false, UnavailableError("linux.do credit payment is not configured", nil)
	}

	notification, err := s.credit.VerifyNotification(values)
	if err != nil {
		if errors.Is(err, linuxdocredit.ErrInvalidSignature) {
			return model.PaymentOrder{}, false, UnauthorizedError("invalid linux.do credit signature")
		}
		return model.PaymentOrder{}, false, ValidationError(err.Error())
	}

	order, err := s.db.GetPaymentOrderByOutTradeNo(ctx, notification.OutTradeNo)
	if err != nil {
		if storage.IsNotFound(err) {
			return model.PaymentOrder{}, false, NotFoundError("payment order not found")
		}
		return model.PaymentOrder{}, false, InternalError("failed to load payment order", err)
	}

	if err := validateGatewayMoney(order.TotalPriceCents, notification.Money); err != nil {
		return model.PaymentOrder{}, false, ValidationError(err.Error())
	}

	orderBefore := order
	now := time.Now().UTC()
	order, err = s.db.UpdatePaymentOrderGatewayState(ctx, storage.UpdatePaymentOrderGatewayStateInput{
		OutTradeNo:       order.OutTradeNo,
		Status:           model.PaymentOrderStatusPaid,
		ProviderTradeNo:  notification.TradeNo,
		NotifyPayloadRaw: encodeValuesJSON(values),
		PaidAt:           &now,
		LastCheckedAt:    &now,
	})
	if err != nil {
		return model.PaymentOrder{}, false, InternalError("failed to mark payment order as paid", err)
	}

	if orderBefore.Status != model.PaymentOrderStatusPaid {
		logAuditWriteFailure("payment.order.gateway_paid", s.db.WriteAuditLog(ctx, storage.AuditLogInput{
			Action:       "payment.order.gateway_paid",
			ResourceType: "payment_order",
			ResourceID:   order.OutTradeNo,
			MetadataJSON: fmt.Sprintf(`{"provider_trade_no":"%s","status":"%s"}`, order.ProviderTradeNo, order.Status),
		}))
	}

	applyInput, err := s.buildApplyPaymentOrderEntitlementInput(ctx, order, now)
	if err != nil {
		failedOrder := s.persistOrderFulfillmentFailure(ctx, order, now, err)
		return failedOrder, false, err
	}
	appliedOrder, applied, err := s.db.ApplyPaymentOrderEntitlement(ctx, applyInput)
	if err != nil {
		failedOrder := s.persistOrderFulfillmentFailure(ctx, order, now, err)
		return failedOrder, false, InternalError("failed to apply payment order entitlement", err)
	}

	if applied {
		logAuditWriteFailure("payment.order.entitlement_applied", s.db.WriteAuditLog(ctx, storage.AuditLogInput{
			ResourceType: "payment_order",
			Action:       "payment.order.entitlement_applied",
			ResourceID:   appliedOrder.OutTradeNo,
			MetadataJSON: fmt.Sprintf(`{"effect_type":"%s","granted_total":%d}`, appliedOrder.EffectType, appliedOrder.GrantedTotal),
		}))
	}

	return appliedOrder, applied, nil
}

// validateOrderCreation resolves the product and enforces the small set of
// business rules that should reject obviously useless purchases.
func (s *PaymentService) validateOrderCreation(ctx context.Context, user model.User, request CreatePaymentOrderRequest) (model.PaymentProduct, int64, error) {
	product, err := s.db.GetPaymentProduct(ctx, strings.TrimSpace(request.ProductKey))
	if err != nil {
		if storage.IsNotFound(err) {
			return model.PaymentProduct{}, 0, NotFoundError("payment product not found")
		}
		return model.PaymentProduct{}, 0, InternalError("failed to load payment product", err)
	}
	if !product.Enabled {
		return model.PaymentProduct{}, 0, ForbiddenError("the selected payment product is currently disabled")
	}
	if product.Key == PaymentProductDomainAllocationPurchase || product.EffectType == model.PaymentEffectDomainAllocationPurchase {
		return model.PaymentProduct{}, 0, ForbiddenError("the selected payment product is reserved for the dedicated domain-purchase checkout flow")
	}
	if request.Units < 1 || request.Units > maxPaymentOrderUnits {
		return model.PaymentProduct{}, 0, ValidationError(fmt.Sprintf("units must be between 1 and %d", maxPaymentOrderUnits))
	}

	switch product.EffectType {
	case model.PaymentEffectEmailCatchAllSubscriptionDays, model.PaymentEffectEmailCatchAllRemainingCount:
		permissionService := NewPermissionService(s.cfg, s.db, nil)
		permission, permissionErr := permissionService.loadEmailCatchAllPermission(ctx, user)
		if permissionErr != nil {
			return model.PaymentProduct{}, 0, permissionErr
		}
		if permission.Status != "approved" {
			if len(permission.EligibilityReasons) > 0 {
				return model.PaymentProduct{}, 0, ForbiddenError(firstNonEmpty(permission.EligibilityReasons...))
			}
			return model.PaymentProduct{}, 0, ForbiddenError("the catch-all email permission must be approved before this product can be purchased")
		}
	}

	return product, request.Units, nil
}

// syncAndApplyOrder opportunistically upgrades a locally pending order using
// the upstream query API and then reapplies entitlements when needed.
func (s *PaymentService) syncAndApplyOrder(ctx context.Context, order model.PaymentOrder) (model.PaymentOrder, error) {
	current := order

	if current.Status != model.PaymentOrderStatusPaid && s.credit != nil && s.credit.Configured() && s.cfg.LinuxDOCreditConfigured() {
		queryResult, err := s.credit.QueryOrder(ctx, current.OutTradeNo)
		switch {
		case err == nil:
			if err := validateGatewayMoney(current.TotalPriceCents, queryResult.Money); err != nil {
				return model.PaymentOrder{}, ValidationError(err.Error())
			}
			now := time.Now().UTC()
			status := current.Status
			if queryResult.Status == 1 {
				status = model.PaymentOrderStatusPaid
			} else if status == model.PaymentOrderStatusCreated && strings.TrimSpace(current.PaymentURL) != "" {
				status = model.PaymentOrderStatusPending
			}

			current, err = s.db.UpdatePaymentOrderGatewayState(ctx, storage.UpdatePaymentOrderGatewayStateInput{
				OutTradeNo:      current.OutTradeNo,
				Status:          status,
				ProviderTradeNo: queryResult.TradeNo,
				PaidAt:          paidAtFromQueryResult(status, current.PaidAt, queryResult),
				LastCheckedAt:   &now,
			})
			if err != nil {
				return model.PaymentOrder{}, InternalError("failed to reconcile payment order", err)
			}
		case errors.Is(err, linuxdocredit.ErrOrderNotFound):
			now := time.Now().UTC()
			current, err = s.db.UpdatePaymentOrderGatewayState(ctx, storage.UpdatePaymentOrderGatewayStateInput{
				OutTradeNo:    current.OutTradeNo,
				Status:        current.Status,
				LastCheckedAt: &now,
			})
			if err != nil {
				return model.PaymentOrder{}, InternalError("failed to touch payment order check timestamp", err)
			}
		default:
			// Query failures should not turn a readable order view into a hard 500
			// when local state already exists. Keep the last known state and let
			// notify retries or later polls converge.
		}
	}

	if current.Status == model.PaymentOrderStatusPaid && current.AppliedAt == nil {
		now := time.Now().UTC()
		applyInput, buildErr := s.buildApplyPaymentOrderEntitlementInput(ctx, current, now)
		if buildErr != nil {
			return s.persistOrderFulfillmentFailure(ctx, current, now, buildErr), nil
		}
		appliedOrder, _, err := s.db.ApplyPaymentOrderEntitlement(ctx, applyInput)
		if err != nil {
			return s.persistOrderFulfillmentFailure(ctx, current, now, err), nil
		}
		current = appliedOrder
	}

	return current, nil
}

// persistOrderFulfillmentFailure records that payment succeeded but the local
// entitlement application failed. Refresh endpoints can then return a readable
// terminal order state instead of leaving the row stuck in a misleading
// paid-but-pending state forever.
func (s *PaymentService) persistOrderFulfillmentFailure(ctx context.Context, order model.PaymentOrder, failedAt time.Time, cause error) model.PaymentOrder {
	if strings.TrimSpace(order.OutTradeNo) == "" {
		return order
	}

	failedOrder, err := s.db.UpdatePaymentOrderFulfillmentState(ctx, storage.UpdatePaymentOrderFulfillmentStateInput{
		OutTradeNo:          order.OutTradeNo,
		FulfillmentStatus:   model.PaymentOrderFulfillmentFailed,
		FulfillmentError:    trimPaymentFulfillmentError(cause),
		FulfillmentFailedAt: &failedAt,
	})
	if err != nil {
		logPostMutationFailure("payment.order.fulfillment_failed", err)
		return order
	}
	return failedOrder
}

// trimPaymentFulfillmentError keeps persisted failure messages human-readable
// while preventing unbounded database growth if a nested dependency returns an
// unusually large error string.
func trimPaymentFulfillmentError(err error) string {
	if err == nil {
		return ""
	}
	message := strings.TrimSpace(err.Error())
	if len(message) <= 500 {
		return message
	}
	return strings.TrimSpace(message[:500])
}

// buildApplyPaymentOrderEntitlementInput enriches domain-purchase grants with
// one real-time Cloudflare occupancy snapshot so the final apply step can stay
// zero-trust even when DNS changed after checkout creation.
func (s *PaymentService) buildApplyPaymentOrderEntitlementInput(ctx context.Context, order model.PaymentOrder, appliedAt time.Time) (storage.ApplyPaymentOrderEntitlementInput, error) {
	input := storage.ApplyPaymentOrderEntitlementInput{
		OutTradeNo: order.OutTradeNo,
		AppliedAt:  appliedAt,
	}
	if order.EffectType != model.PaymentEffectDomainAllocationPurchase {
		return input, nil
	}

	blockedPrefixes, err := s.listLiveDomainPurchaseBlockedPrefixes(ctx, order.PurchaseRootDomain)
	if err != nil {
		return storage.ApplyPaymentOrderEntitlementInput{}, err
	}
	input.BlockedNormalizedPrefixes = blockedPrefixes
	reservedUserPrefixes, err := s.listReservedDynamicMailAliasUserPrefixes(ctx, order.PurchaseRootDomain)
	if err != nil {
		return storage.ApplyPaymentOrderEntitlementInput{}, err
	}
	input.ReservedDynamicMailAliasUserPrefixes = reservedUserPrefixes
	return input, nil
}

// buildPaymentOrderTitle generates the gateway-visible order title.
func buildPaymentOrderTitle(product model.PaymentProduct, units int64) string {
	if units <= 1 {
		return product.DisplayName
	}
	return fmt.Sprintf("%s x%d", product.DisplayName, units)
}

// generateOutTradeNo creates a compact unique business order number that stays
// URL-safe and human-readable in logs and callback parameters.
func generateOutTradeNo() (string, error) {
	randomToken, err := security.RandomToken(9)
	if err != nil {
		return "", err
	}
	sanitized := strings.ToUpper(strings.ReplaceAll(strings.ReplaceAll(randomToken, "-", ""), "_", ""))
	if len(sanitized) > 12 {
		sanitized = sanitized[:12]
	}
	return fmt.Sprintf("LDC%s%s", time.Now().UTC().Format("20060102150405"), sanitized), nil
}

// parseMoneyToCents parses one operator-facing LDC amount string with at most
// two fractional digits into integer cents.
func parseMoneyToCents(raw string) (int64, error) {
	value := strings.TrimSpace(raw)
	if value == "" {
		return 0, fmt.Errorf("unit_price is required")
	}
	if strings.HasPrefix(value, "+") {
		value = strings.TrimPrefix(value, "+")
	}
	if strings.HasPrefix(value, "-") {
		return 0, fmt.Errorf("unit_price must be greater than 0")
	}

	wholePart, fractionalPart, hasFraction := strings.Cut(value, ".")
	if wholePart == "" {
		wholePart = "0"
	}
	if wholePart == "" || !digitsOnly(wholePart) {
		return 0, fmt.Errorf("unit_price must be a valid decimal amount")
	}
	if hasFraction {
		if fractionalPart == "" || len(fractionalPart) > 2 || !digitsOnly(fractionalPart) {
			return 0, fmt.Errorf("unit_price may have at most two decimal places")
		}
	}

	wholeValue, err := strconv.ParseInt(wholePart, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("unit_price is too large")
	}
	cents := wholeValue * 100
	if hasFraction {
		if len(fractionalPart) == 1 {
			fractionalPart += "0"
		}
		fractionalValue, fractionErr := strconv.ParseInt(fractionalPart, 10, 64)
		if fractionErr != nil {
			return 0, fmt.Errorf("unit_price is too large")
		}
		cents += fractionalValue
	}
	return cents, nil
}

// formatMoneyFromCents converts integer cents into the gateway's `money`
// string format, trimming unnecessary trailing zeros while preserving 2-digit
// precision when needed.
func formatMoneyFromCents(cents int64) string {
	sign := ""
	if cents < 0 {
		sign = "-"
		cents = -cents
	}
	whole := cents / 100
	fraction := cents % 100
	if fraction == 0 {
		return sign + strconv.FormatInt(whole, 10)
	}
	return fmt.Sprintf("%s%d.%02d", sign, whole, fraction)
}

// validateGatewayMoney rejects callbacks or query responses whose amount does
// not match the locally recorded order total.
func validateGatewayMoney(expectedCents int64, gatewayMoney string) error {
	actualCents, err := parseMoneyToCents(gatewayMoney)
	if err != nil {
		return fmt.Errorf("gateway returned an invalid money value")
	}
	if actualCents != expectedCents {
		return fmt.Errorf("gateway money %s does not match local order total %s", formatMoneyFromCents(actualCents), formatMoneyFromCents(expectedCents))
	}
	return nil
}

// paidAtFromQueryResult keeps a stable paid timestamp once one order is already
// marked paid while still filling it on the first successful query.
func paidAtFromQueryResult(status string, currentPaidAt *time.Time, _ linuxdocredit.QueryOrderResult) *time.Time {
	if status != model.PaymentOrderStatusPaid {
		return currentPaidAt
	}
	if currentPaidAt != nil {
		return currentPaidAt
	}
	now := time.Now().UTC()
	return &now
}

// encodeValuesJSON stores one callback payload in a stable JSON form for later
// operator inspection without keeping the raw query string ordering.
func encodeValuesJSON(values url.Values) string {
	if len(values) == 0 {
		return ""
	}
	payload := make(map[string][]string, len(values))
	for key, entries := range values {
		copied := append([]string(nil), entries...)
		payload[key] = copied
	}
	data, err := json.Marshal(payload)
	if err != nil {
		return ""
	}
	return string(data)
}

// digitsOnly keeps money parsing strict and predictable.
func digitsOnly(value string) bool {
	for _, runeValue := range value {
		if runeValue < '0' || runeValue > '9' {
			return false
		}
	}
	return value != ""
}

// multiplyInt64Checked prevents grant and price calculations from silently
// overflowing when callers request extremely large unit counts.
func multiplyInt64Checked(left int64, right int64) (int64, error) {
	if left == 0 || right == 0 {
		return 0, nil
	}
	if left > math.MaxInt64/right {
		return 0, fmt.Errorf("int64 overflow")
	}
	return left * right, nil
}
