package config

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"strings"
	"time"
)

// Config groups all runtime configuration needed by the backend process.
type Config struct {
	App         AppConfig
	SQLite      SQLiteConfig
	LinuxDO     LinuxDOConfig
	Cloudflare  CloudflareConfig
	LoadedAtUTC time.Time
}

// AppConfig stores generic application, networking, and session settings.
type AppConfig struct {
	Name                  string
	Env                   string
	Addr                  string
	BaseURL               string
	FrontendURL           string
	AdminFrontendURL      string
	AllowedOrigins        []string
	SessionCookieName     string
	SessionSecret         []byte
	SessionTTL            time.Duration
	SessionSecure         bool
	SessionBindUserAgent  bool
	AutoGenerateDevSecret bool
	AdminUsernames        []string
	AdminPassword         string
	ReadTimeout           time.Duration
	WriteTimeout          time.Duration
	IdleTimeout           time.Duration
}

// SQLiteConfig stores the SQLite database path.
type SQLiteConfig struct {
	Path string
}

// LinuxDOConfig stores Linux Do OAuth settings.
type LinuxDOConfig struct {
	ClientID     string
	ClientSecret string
	RedirectURL  string
	AuthorizeURL string
	TokenURL     string
	UserInfoURL  string
	Scope        string
	EnablePKCE   bool
}

// CloudflareConfig stores Cloudflare API and domain defaults.
type CloudflareConfig struct {
	APIToken            string
	DefaultRootDomain   string
	DefaultZoneID       string
	AutoBootstrapDomain bool
	DefaultUserQuota    int
}

// Load reads configuration from environment variables and applies defaults.
func Load() (Config, error) {
	cfg := Config{
		App: AppConfig{
			Name:                  getEnv("APP_NAME", "LinuxDoSpace"),
			Env:                   getEnv("APP_ENV", "development"),
			Addr:                  getEnv("APP_ADDR", ":8080"),
			BaseURL:               getEnv("APP_BASE_URL", "http://localhost:8080"),
			FrontendURL:           getEnv("APP_FRONTEND_URL", "http://localhost:3000"),
			AdminFrontendURL:      getEnv("APP_ADMIN_FRONTEND_URL", "http://localhost:3001"),
			AllowedOrigins:        splitCSV(getEnv("APP_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:3001")),
			SessionCookieName:     getEnv("APP_SESSION_COOKIE_NAME", "linuxdospace_session"),
			SessionTTL:            mustParseDuration(getEnv("APP_SESSION_TTL", "24h")),
			SessionSecure:         mustParseBool(getEnv("APP_SESSION_SECURE", "false")),
			SessionBindUserAgent:  mustParseBool(getEnv("APP_SESSION_BIND_USER_AGENT", "true")),
			AutoGenerateDevSecret: mustParseBool(getEnv("APP_AUTO_GENERATE_DEV_SECRET", "true")),
			AdminUsernames:        splitCSV(os.Getenv("APP_ADMIN_USERNAMES")),
			AdminPassword:         strings.TrimSpace(os.Getenv("APP_ADMIN_PASSWORD")),
			ReadTimeout:           mustParseDuration(getEnv("APP_READ_TIMEOUT", "15s")),
			WriteTimeout:          mustParseDuration(getEnv("APP_WRITE_TIMEOUT", "15s")),
			IdleTimeout:           mustParseDuration(getEnv("APP_IDLE_TIMEOUT", "60s")),
		},
		SQLite: SQLiteConfig{
			Path: getEnv("SQLITE_PATH", "./data/linuxdospace.sqlite"),
		},
		LinuxDO: LinuxDOConfig{
			ClientID:     strings.TrimSpace(os.Getenv("LINUXDO_OAUTH_CLIENT_ID")),
			ClientSecret: strings.TrimSpace(os.Getenv("LINUXDO_OAUTH_CLIENT_SECRET")),
			RedirectURL:  getEnv("LINUXDO_OAUTH_REDIRECT_URL", "http://localhost:8080/v1/auth/callback"),
			AuthorizeURL: getEnv("LINUXDO_OAUTH_AUTHORIZE_URL", "https://connect.linux.do/oauth2/authorize"),
			TokenURL:     getEnv("LINUXDO_OAUTH_TOKEN_URL", "https://connect.linux.do/oauth2/token"),
			UserInfoURL:  getEnv("LINUXDO_OAUTH_USERINFO_URL", "https://connect.linux.do/api/user"),
			Scope:        getEnv("LINUXDO_OAUTH_SCOPE", "user"),
			EnablePKCE:   mustParseBool(getEnv("LINUXDO_OAUTH_ENABLE_PKCE", "false")),
		},
		Cloudflare: CloudflareConfig{
			APIToken:            strings.TrimSpace(os.Getenv("CLOUDFLARE_API_TOKEN")),
			DefaultRootDomain:   getEnv("CLOUDFLARE_DEFAULT_ROOT_DOMAIN", "linuxdo.space"),
			DefaultZoneID:       strings.TrimSpace(os.Getenv("CLOUDFLARE_DEFAULT_ZONE_ID")),
			AutoBootstrapDomain: mustParseBool(getEnv("CLOUDFLARE_AUTO_BOOTSTRAP_DOMAIN", "true")),
			DefaultUserQuota:    mustParseInt(getEnv("CLOUDFLARE_DEFAULT_USER_QUOTA", "1")),
		},
		LoadedAtUTC: time.Now().UTC(),
	}

	if secret := strings.TrimSpace(os.Getenv("APP_SESSION_SECRET")); secret != "" {
		cfg.App.SessionSecret = []byte(secret)
	} else if cfg.App.Env != "production" && cfg.App.AutoGenerateDevSecret {
		generated, err := generateDevSecret()
		if err != nil {
			return Config{}, fmt.Errorf("generate development session secret: %w", err)
		}
		cfg.App.SessionSecret = generated
	} else {
		return Config{}, fmt.Errorf("APP_SESSION_SECRET is required when auto generation is disabled or APP_ENV=production")
	}

	if cfg.Cloudflare.DefaultUserQuota < 1 {
		return Config{}, fmt.Errorf("CLOUDFLARE_DEFAULT_USER_QUOTA must be at least 1")
	}

	if err := validateAdminConfig(cfg.App); err != nil {
		return Config{}, err
	}

	return cfg, nil
}

// OAuthConfigured reports whether Linux Do OAuth has the minimum configuration.
func (c Config) OAuthConfigured() bool {
	return c.LinuxDO.ClientID != "" && c.LinuxDO.ClientSecret != "" && c.LinuxDO.RedirectURL != ""
}

// CloudflareConfigured reports whether Cloudflare API access is configured.
func (c Config) CloudflareConfigured() bool {
	return c.Cloudflare.APIToken != ""
}

// getEnv returns a trimmed environment variable or a fallback value.
func getEnv(key string, fallback string) string {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	return value
}

// splitCSV turns a comma-separated string into a trimmed string slice.
func splitCSV(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return nil
	}

	parts := strings.Split(raw, ",")
	values := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed == "" {
			continue
		}
		values = append(values, trimmed)
	}
	return values
}

// mustParseDuration parses a duration and panics on invalid controlled defaults.
func mustParseDuration(raw string) time.Duration {
	value, err := time.ParseDuration(strings.TrimSpace(raw))
	if err != nil {
		panic(fmt.Sprintf("invalid duration %q: %v", raw, err))
	}
	return value
}

// mustParseBool parses a boolean-like environment value.
func mustParseBool(raw string) bool {
	normalized := strings.ToLower(strings.TrimSpace(raw))
	switch normalized {
	case "1", "true", "yes", "on":
		return true
	case "0", "false", "no", "off":
		return false
	default:
		panic(fmt.Sprintf("invalid bool %q", raw))
	}
}

// mustParseInt parses an integer environment value.
func mustParseInt(raw string) int {
	var value int
	if _, err := fmt.Sscanf(strings.TrimSpace(raw), "%d", &value); err != nil {
		panic(fmt.Sprintf("invalid int %q: %v", raw, err))
	}
	return value
}

// generateDevSecret creates a random session secret for local development.
func generateDevSecret() ([]byte, error) {
	buffer := make([]byte, 32)
	if _, err := rand.Read(buffer); err != nil {
		return nil, err
	}
	encoded := base64.RawURLEncoding.EncodeToString(buffer)
	return []byte(encoded), nil
}

// validateAdminConfig keeps the administrator console fail-closed unless the
// deployment explicitly provides both the admin allowlist and the second-factor
// password.
func validateAdminConfig(app AppConfig) error {
	hasAdmins := len(app.AdminUsernames) > 0
	hasPassword := strings.TrimSpace(app.AdminPassword) != ""

	if app.Env == "production" && (!hasAdmins || !hasPassword) {
		return fmt.Errorf("APP_ADMIN_USERNAMES and APP_ADMIN_PASSWORD are required when APP_ENV=production")
	}

	if hasAdmins && !hasPassword {
		return fmt.Errorf("APP_ADMIN_PASSWORD is required when APP_ADMIN_USERNAMES is configured")
	}

	if !hasAdmins && hasPassword {
		return fmt.Errorf("APP_ADMIN_USERNAMES is required when APP_ADMIN_PASSWORD is configured")
	}

	return nil
}
