package config

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"strings"
	"time"
)

// Config 是整个后端进程的集中配置对象。
// 我们将配置拆分为多个子结构，目的是让每一类配置的职责边界清晰且更容易维护。
type Config struct {
	App         AppConfig
	SQLite      SQLiteConfig
	LinuxDO     LinuxDOConfig
	Cloudflare  CloudflareConfig
	LoadedAtUTC time.Time
}

// AppConfig 保存应用自身的网络、会话和通用行为配置。
type AppConfig struct {
	Name                  string
	Env                   string
	Addr                  string
	BaseURL               string
	FrontendURL           string
	AllowedOrigins        []string
	SessionCookieName     string
	SessionSecret         []byte
	SessionTTL            time.Duration
	SessionSecure         bool
	SessionBindUserAgent  bool
	AutoGenerateDevSecret bool
	AdminUsernames        []string
	ReadTimeout           time.Duration
	WriteTimeout          time.Duration
	IdleTimeout           time.Duration
}

// SQLiteConfig 保存 SQLite 数据库路径配置。
type SQLiteConfig struct {
	Path string
}

// LinuxDOConfig 保存 Linux Do OAuth 相关配置。
type LinuxDOConfig struct {
	ClientID     string
	ClientSecret string
	RedirectURL  string
	AuthorizeURL string
	TokenURL     string
	UserInfoURL  string
	Scope        string
	EnablePKCE   bool
}

// CloudflareConfig 保存 Cloudflare API 与默认域名配置。
type CloudflareConfig struct {
	APIToken            string
	DefaultRootDomain   string
	DefaultZoneID       string
	AutoBootstrapDomain bool
	DefaultUserQuota    int
}

// Load 从环境变量读取配置，并填充默认值。
// 这里不会强制要求所有第三方配置都存在，因为开发阶段可能只想先运行本地骨架。
func Load() (Config, error) {
	cfg := Config{
		App: AppConfig{
			Name:                  getEnv("APP_NAME", "LinuxDoSpace"),
			Env:                   getEnv("APP_ENV", "development"),
			Addr:                  getEnv("APP_ADDR", ":8080"),
			BaseURL:               getEnv("APP_BASE_URL", "http://localhost:8080"),
			FrontendURL:           getEnv("APP_FRONTEND_URL", "http://localhost:3000"),
			AllowedOrigins:        splitCSV(getEnv("APP_ALLOWED_ORIGINS", "http://localhost:3000")),
			SessionCookieName:     getEnv("APP_SESSION_COOKIE_NAME", "linuxdospace_session"),
			SessionTTL:            mustParseDuration(getEnv("APP_SESSION_TTL", "24h")),
			SessionSecure:         mustParseBool(getEnv("APP_SESSION_SECURE", "false")),
			SessionBindUserAgent:  mustParseBool(getEnv("APP_SESSION_BIND_USER_AGENT", "true")),
			AutoGenerateDevSecret: mustParseBool(getEnv("APP_AUTO_GENERATE_DEV_SECRET", "true")),
			AdminUsernames:        splitCSV(getEnv("APP_ADMIN_USERNAMES", "")),
			ReadTimeout:           mustParseDuration(getEnv("APP_READ_TIMEOUT", "15s")),
			WriteTimeout:          mustParseDuration(getEnv("APP_WRITE_TIMEOUT", "15s")),
			IdleTimeout:           mustParseDuration(getEnv("APP_IDLE_TIMEOUT", "60s")),
		},
		SQLite: SQLiteConfig{
			Path: getEnv("SQLITE_PATH", "./data/linuxdospace.sqlite"),
		},
		LinuxDO: LinuxDOConfig{
			ClientID:     strings.TrimSpace(os.Getenv("LINUXDO_OAUTH_CLIENT_ID")),
			ClientSecret: strings.TrimSpace(os.Getenv("LINUXDO_OAUTH_CLIENT_SECRET")),
			RedirectURL:  getEnv("LINUXDO_OAUTH_REDIRECT_URL", "http://localhost:8080/v1/auth/callback"),
			AuthorizeURL: getEnv("LINUXDO_OAUTH_AUTHORIZE_URL", "https://connect.linux.do/oauth2/authorize"),
			TokenURL:     getEnv("LINUXDO_OAUTH_TOKEN_URL", "https://connect.linux.do/oauth2/access_token"),
			UserInfoURL:  getEnv("LINUXDO_OAUTH_USERINFO_URL", "https://connect.linux.do/api/user"),
			Scope:        strings.TrimSpace(os.Getenv("LINUXDO_OAUTH_SCOPE")),
			EnablePKCE:   mustParseBool(getEnv("LINUXDO_OAUTH_ENABLE_PKCE", "false")),
		},
		Cloudflare: CloudflareConfig{
			APIToken:            strings.TrimSpace(os.Getenv("CLOUDFLARE_API_TOKEN")),
			DefaultRootDomain:   getEnv("CLOUDFLARE_DEFAULT_ROOT_DOMAIN", "linuxdo.space"),
			DefaultZoneID:       strings.TrimSpace(os.Getenv("CLOUDFLARE_DEFAULT_ZONE_ID")),
			AutoBootstrapDomain: mustParseBool(getEnv("CLOUDFLARE_AUTO_BOOTSTRAP_DOMAIN", "true")),
			DefaultUserQuota:    mustParseInt(getEnv("CLOUDFLARE_DEFAULT_USER_QUOTA", "1")),
		},
		LoadedAtUTC: time.Now().UTC(),
	}

	// 允许开发环境在未提供会话密钥时自动生成临时密钥，方便本地快速启动。
	if secret := strings.TrimSpace(os.Getenv("APP_SESSION_SECRET")); secret != "" {
		cfg.App.SessionSecret = []byte(secret)
	} else if cfg.App.Env != "production" && cfg.App.AutoGenerateDevSecret {
		generated, err := generateDevSecret()
		if err != nil {
			return Config{}, fmt.Errorf("generate development session secret: %w", err)
		}
		cfg.App.SessionSecret = generated
	} else {
		return Config{}, fmt.Errorf("APP_SESSION_SECRET is required when auto generation is disabled or APP_ENV=production")
	}

	if cfg.Cloudflare.DefaultUserQuota < 1 {
		return Config{}, fmt.Errorf("CLOUDFLARE_DEFAULT_USER_QUOTA must be at least 1")
	}

	return cfg, nil
}

// OAuthConfigured 返回 Linux Do OAuth 是否已具备最小可运行配置。
func (c Config) OAuthConfigured() bool {
	return c.LinuxDO.ClientID != "" && c.LinuxDO.ClientSecret != "" && c.LinuxDO.RedirectURL != ""
}

// CloudflareConfigured 返回 Cloudflare API 是否可用。
func (c Config) CloudflareConfigured() bool {
	return c.Cloudflare.APIToken != ""
}

// getEnv 用于从环境变量读取值，并在缺失时使用默认值。
func getEnv(key string, fallback string) string {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	return value
}

// splitCSV 把逗号分隔的字符串转为切片，并自动去除空白和空项。
func splitCSV(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return nil
	}

	parts := strings.Split(raw, ",")
	values := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed == "" {
			continue
		}
		values = append(values, trimmed)
	}
	return values
}

// mustParseDuration 把字符串解析成 time.Duration。
// 由于默认值已经是受控数据，因此这里使用 panic 来暴露开发期配置错误。
func mustParseDuration(raw string) time.Duration {
	value, err := time.ParseDuration(strings.TrimSpace(raw))
	if err != nil {
		panic(fmt.Sprintf("invalid duration %q: %v", raw, err))
	}
	return value
}

// mustParseBool 把字符串解析为布尔值。
func mustParseBool(raw string) bool {
	normalized := strings.ToLower(strings.TrimSpace(raw))
	switch normalized {
	case "1", "true", "yes", "on":
		return true
	case "0", "false", "no", "off":
		return false
	default:
		panic(fmt.Sprintf("invalid bool %q", raw))
	}
}

// mustParseInt 把字符串解析为整数。
func mustParseInt(raw string) int {
	var value int
	if _, err := fmt.Sscanf(strings.TrimSpace(raw), "%d", &value); err != nil {
		panic(fmt.Sprintf("invalid int %q: %v", raw, err))
	}
	return value
}

// generateDevSecret 为开发环境生成一次性的会话密钥。
func generateDevSecret() ([]byte, error) {
	buffer := make([]byte, 32)
	if _, err := rand.Read(buffer); err != nil {
		return nil, err
	}
	encoded := base64.RawURLEncoding.EncodeToString(buffer)
	return []byte(encoded), nil
}
