package config

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"net/netip"
	"os"
	"strings"
	"time"
)

// Config groups all runtime configuration needed by the backend process.
type Config struct {
	App         AppConfig
	Database    DatabaseConfig
	LinuxDO     LinuxDOConfig
	Cloudflare  CloudflareConfig
	Mail        MailConfig
	LoadedAtUTC time.Time
}

// AppConfig stores generic application, networking, and session settings.
type AppConfig struct {
	Name                  string
	Env                   string
	Addr                  string
	BaseURL               string
	FrontendURL           string
	AdminFrontendURL      string
	AllowedOrigins        []string
	SessionCookieName     string
	SessionSecret         []byte
	SessionTTL            time.Duration
	AdminVerificationTTL  time.Duration
	SessionSecure         bool
	SessionBindUserAgent  bool
	AutoGenerateDevSecret bool
	AdminUsernames        []string
	AdminPassword         string
	TrustedProxyCIDRs     []netip.Prefix
	ReadTimeout           time.Duration
	WriteTimeout          time.Duration
	IdleTimeout           time.Duration
}

// DatabaseConfig stores the selected database backend and its connection
// settings.
type DatabaseConfig struct {
	Driver      string
	SQLitePath  string
	PostgresDSN string
}

// LinuxDOConfig stores Linux Do OAuth settings.
type LinuxDOConfig struct {
	ClientID     string
	ClientSecret string
	RedirectURL  string
	AuthorizeURL string
	TokenURL     string
	UserInfoURL  string
	Scope        string
	EnablePKCE   bool
}

// CloudflareConfig stores Cloudflare API and domain defaults.
type CloudflareConfig struct {
	AccountID           string
	APIToken            string
	DefaultRootDomain   string
	DefaultZoneID       string
	AutoBootstrapDomain bool
	DefaultUserQuota    int
}

const (
	// EmailForwardingBackendCloudflare keeps the historical behavior where the
	// backend writes forwarding rules directly into Cloudflare Email Routing.
	EmailForwardingBackendCloudflare = "cloudflare"

	// EmailForwardingBackendDatabaseRelay stores mailbox routes only in the
	// database and lets the application receive + forward SMTP traffic itself.
	EmailForwardingBackendDatabaseRelay = "database_relay"
)

// MailConfig stores the email-forwarding execution mode and the SMTP relay
// settings used when LinuxDoSpace receives mail itself.
type MailConfig struct {
	ForwardingBackend string
	RelayEnabled      bool
	SMTPAddr          string
	Domain            string
	MaxRecipients     int
	MaxMessageBytes   int64
	ReadTimeout       time.Duration
	WriteTimeout      time.Duration
	ForwardHost       string
	ForwardUsername   string
	ForwardPassword   string
	ForwardFrom       string
}

// Load reads configuration from environment variables and applies defaults.
func Load() (Config, error) {
	cfg := Config{
		App: AppConfig{
			Name:                  getEnv("APP_NAME", "LinuxDoSpace"),
			Env:                   getEnv("APP_ENV", "development"),
			Addr:                  getEnv("APP_ADDR", ":8080"),
			BaseURL:               getEnv("APP_BASE_URL", "http://localhost:8080"),
			FrontendURL:           getEnv("APP_FRONTEND_URL", "http://localhost:3000"),
			AdminFrontendURL:      getEnv("APP_ADMIN_FRONTEND_URL", "http://localhost:3001"),
			AllowedOrigins:        splitCSV(getEnv("APP_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:3001")),
			SessionCookieName:     getEnv("APP_SESSION_COOKIE_NAME", "linuxdospace_session"),
			SessionTTL:            mustParseDuration(getEnv("APP_SESSION_TTL", "24h")),
			AdminVerificationTTL:  mustParseDuration(getEnv("APP_ADMIN_VERIFICATION_TTL", "30m")),
			SessionSecure:         mustParseBool(getEnv("APP_SESSION_SECURE", "false")),
			SessionBindUserAgent:  mustParseBool(getEnv("APP_SESSION_BIND_USER_AGENT", "true")),
			AutoGenerateDevSecret: mustParseBool(getEnv("APP_AUTO_GENERATE_DEV_SECRET", "true")),
			AdminUsernames:        splitCSV(os.Getenv("APP_ADMIN_USERNAMES")),
			AdminPassword:         strings.TrimSpace(os.Getenv("APP_ADMIN_PASSWORD")),
			TrustedProxyCIDRs:     mustParseCIDRs(getEnv("APP_TRUSTED_PROXY_CIDRS", "127.0.0.1/32,::1/128")),
			ReadTimeout:           mustParseDuration(getEnv("APP_READ_TIMEOUT", "15s")),
			WriteTimeout:          mustParseDuration(getEnv("APP_WRITE_TIMEOUT", "15s")),
			IdleTimeout:           mustParseDuration(getEnv("APP_IDLE_TIMEOUT", "60s")),
		},
		Database: DatabaseConfig{
			Driver:      strings.ToLower(getEnv("DATABASE_DRIVER", "sqlite")),
			SQLitePath:  getEnv("SQLITE_PATH", "./data/linuxdospace.sqlite"),
			PostgresDSN: firstNonEmptyEnv("DATABASE_POSTGRES_DSN", "DATABASE_URL"),
		},
		LinuxDO: LinuxDOConfig{
			ClientID:     strings.TrimSpace(os.Getenv("LINUXDO_OAUTH_CLIENT_ID")),
			ClientSecret: strings.TrimSpace(os.Getenv("LINUXDO_OAUTH_CLIENT_SECRET")),
			RedirectURL:  getEnv("LINUXDO_OAUTH_REDIRECT_URL", "http://localhost:8080/v1/auth/callback"),
			AuthorizeURL: getEnv("LINUXDO_OAUTH_AUTHORIZE_URL", "https://connect.linux.do/oauth2/authorize"),
			TokenURL:     getEnv("LINUXDO_OAUTH_TOKEN_URL", "https://connect.linux.do/oauth2/token"),
			UserInfoURL:  getEnv("LINUXDO_OAUTH_USERINFO_URL", "https://connect.linux.do/api/user"),
			Scope:        getEnv("LINUXDO_OAUTH_SCOPE", "user"),
			EnablePKCE:   mustParseBool(getEnv("LINUXDO_OAUTH_ENABLE_PKCE", "false")),
		},
		Cloudflare: CloudflareConfig{
			AccountID:           strings.TrimSpace(os.Getenv("CLOUDFLARE_ACCOUNT_ID")),
			APIToken:            strings.TrimSpace(os.Getenv("CLOUDFLARE_API_TOKEN")),
			DefaultRootDomain:   getEnv("CLOUDFLARE_DEFAULT_ROOT_DOMAIN", "linuxdo.space"),
			DefaultZoneID:       strings.TrimSpace(os.Getenv("CLOUDFLARE_DEFAULT_ZONE_ID")),
			AutoBootstrapDomain: mustParseBool(getEnv("CLOUDFLARE_AUTO_BOOTSTRAP_DOMAIN", "true")),
			DefaultUserQuota:    mustParseInt(getEnv("CLOUDFLARE_DEFAULT_USER_QUOTA", "1")),
		},
		Mail: MailConfig{
			ForwardingBackend: strings.ToLower(getEnv("EMAIL_FORWARDING_BACKEND", EmailForwardingBackendCloudflare)),
			RelayEnabled:      mustParseBool(getEnv("MAIL_RELAY_ENABLED", "false")),
			SMTPAddr:          getEnv("MAIL_RELAY_SMTP_ADDR", ":2525"),
			Domain:            getEnv("MAIL_RELAY_DOMAIN", "mail.linuxdo.space"),
			MaxRecipients:     mustParseInt(getEnv("MAIL_RELAY_MAX_RECIPIENTS", "50")),
			MaxMessageBytes:   mustParseInt64(getEnv("MAIL_RELAY_MAX_MESSAGE_BYTES", "26214400")),
			ReadTimeout:       mustParseDuration(getEnv("MAIL_RELAY_READ_TIMEOUT", "30s")),
			WriteTimeout:      mustParseDuration(getEnv("MAIL_RELAY_WRITE_TIMEOUT", "30s")),
			ForwardHost:       strings.TrimSpace(os.Getenv("MAIL_RELAY_FORWARD_HOST")),
			ForwardUsername:   strings.TrimSpace(os.Getenv("MAIL_RELAY_FORWARD_USERNAME")),
			ForwardPassword:   strings.TrimSpace(os.Getenv("MAIL_RELAY_FORWARD_PASSWORD")),
			ForwardFrom:       strings.TrimSpace(os.Getenv("MAIL_RELAY_FORWARD_FROM")),
		},
		LoadedAtUTC: time.Now().UTC(),
	}

	if secret := strings.TrimSpace(os.Getenv("APP_SESSION_SECRET")); secret != "" {
		cfg.App.SessionSecret = []byte(secret)
	} else if cfg.App.Env != "production" && cfg.App.AutoGenerateDevSecret {
		generated, err := generateDevSecret()
		if err != nil {
			return Config{}, fmt.Errorf("generate development session secret: %w", err)
		}
		cfg.App.SessionSecret = generated
	} else {
		return Config{}, fmt.Errorf("APP_SESSION_SECRET is required when auto generation is disabled or APP_ENV=production")
	}

	if cfg.Cloudflare.DefaultUserQuota < 1 {
		return Config{}, fmt.Errorf("CLOUDFLARE_DEFAULT_USER_QUOTA must be at least 1")
	}
	if err := validateDatabaseConfig(cfg.Database); err != nil {
		return Config{}, err
	}
	if err := validateMailConfig(cfg.Mail); err != nil {
		return Config{}, err
	}
	if cfg.App.AdminVerificationTTL <= 0 {
		return Config{}, fmt.Errorf("APP_ADMIN_VERIFICATION_TTL must be greater than 0")
	}

	if err := validateAdminConfig(cfg.App); err != nil {
		return Config{}, err
	}

	return cfg, nil
}

// OAuthConfigured reports whether Linux Do OAuth has the minimum configuration.
func (c Config) OAuthConfigured() bool {
	return c.LinuxDO.ClientID != "" && c.LinuxDO.ClientSecret != "" && c.LinuxDO.RedirectURL != ""
}

// CloudflareConfigured reports whether Cloudflare API access is configured.
func (c Config) CloudflareConfigured() bool {
	return c.Cloudflare.APIToken != ""
}

// UsesDatabaseMailRelay reports whether email forwarding should be resolved
// from the local database and executed by the built-in SMTP relay.
func (c Config) UsesDatabaseMailRelay() bool {
	return strings.EqualFold(strings.TrimSpace(c.Mail.ForwardingBackend), EmailForwardingBackendDatabaseRelay)
}

// getEnv returns a trimmed environment variable or a fallback value.
func getEnv(key string, fallback string) string {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	return value
}

// firstNonEmptyEnv returns the first non-empty trimmed value among the provided
// environment variables. It allows PostgreSQL deployments to use either the
// explicit project variable or the more common DATABASE_URL convention.
func firstNonEmptyEnv(keys ...string) string {
	for _, key := range keys {
		if value := strings.TrimSpace(os.Getenv(key)); value != "" {
			return value
		}
	}
	return ""
}

// splitCSV turns a comma-separated string into a trimmed string slice.
func splitCSV(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return nil
	}

	parts := strings.Split(raw, ",")
	values := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed == "" {
			continue
		}
		values = append(values, trimmed)
	}
	return values
}

// mustParseDuration parses a duration and panics on invalid controlled defaults.
func mustParseDuration(raw string) time.Duration {
	value, err := time.ParseDuration(strings.TrimSpace(raw))
	if err != nil {
		panic(fmt.Sprintf("invalid duration %q: %v", raw, err))
	}
	return value
}

// mustParseBool parses a boolean-like environment value.
func mustParseBool(raw string) bool {
	normalized := strings.ToLower(strings.TrimSpace(raw))
	switch normalized {
	case "1", "true", "yes", "on":
		return true
	case "0", "false", "no", "off":
		return false
	default:
		panic(fmt.Sprintf("invalid bool %q", raw))
	}
}

// mustParseInt parses an integer environment value.
func mustParseInt(raw string) int {
	var value int
	if _, err := fmt.Sscanf(strings.TrimSpace(raw), "%d", &value); err != nil {
		panic(fmt.Sprintf("invalid int %q: %v", raw, err))
	}
	return value
}

// mustParseInt64 parses one integer value that may exceed the platform-sized
// `int`, such as maximum accepted SMTP message bytes.
func mustParseInt64(raw string) int64 {
	var value int64
	if _, err := fmt.Sscanf(strings.TrimSpace(raw), "%d", &value); err != nil {
		panic(fmt.Sprintf("invalid int64 %q: %v", raw, err))
	}
	return value
}

// mustParseCIDRs parses one comma-separated CIDR allowlist used for trusted
// reverse proxies. Invalid values are treated as configuration bugs and panic
// immediately so production never starts with a silently weakened trust model.
func mustParseCIDRs(raw string) []netip.Prefix {
	parts := splitCSV(raw)
	prefixes := make([]netip.Prefix, 0, len(parts))
	for _, part := range parts {
		prefix, err := netip.ParsePrefix(strings.TrimSpace(part))
		if err != nil {
			panic(fmt.Sprintf("invalid cidr %q: %v", part, err))
		}
		prefixes = append(prefixes, prefix)
	}
	return prefixes
}

// generateDevSecret creates a random session secret for local development.
func generateDevSecret() ([]byte, error) {
	buffer := make([]byte, 32)
	if _, err := rand.Read(buffer); err != nil {
		return nil, err
	}
	encoded := base64.RawURLEncoding.EncodeToString(buffer)
	return []byte(encoded), nil
}

// validateAdminConfig keeps the administrator console fail-closed unless the
// deployment explicitly provides both the admin allowlist and the second-factor
// password.
func validateAdminConfig(app AppConfig) error {
	hasAdmins := len(app.AdminUsernames) > 0
	hasPassword := strings.TrimSpace(app.AdminPassword) != ""

	if app.Env == "production" && (!hasAdmins || !hasPassword) {
		return fmt.Errorf("APP_ADMIN_USERNAMES and APP_ADMIN_PASSWORD are required when APP_ENV=production")
	}

	if hasAdmins && !hasPassword {
		return fmt.Errorf("APP_ADMIN_PASSWORD is required when APP_ADMIN_USERNAMES is configured")
	}

	if !hasAdmins && hasPassword {
		return fmt.Errorf("APP_ADMIN_USERNAMES is required when APP_ADMIN_PASSWORD is configured")
	}

	return nil
}

// validateDatabaseConfig keeps startup fail-closed so production never silently
// boots with the wrong database backend.
func validateDatabaseConfig(database DatabaseConfig) error {
	switch database.Driver {
	case "sqlite":
		if strings.TrimSpace(database.SQLitePath) == "" {
			return fmt.Errorf("SQLITE_PATH is required when DATABASE_DRIVER=sqlite")
		}
	case "postgres":
		if strings.TrimSpace(database.PostgresDSN) == "" {
			return fmt.Errorf("DATABASE_POSTGRES_DSN or DATABASE_URL is required when DATABASE_DRIVER=postgres")
		}
	default:
		return fmt.Errorf("DATABASE_DRIVER must be one of sqlite, postgres")
	}

	return nil
}

// validateMailConfig keeps the selected forwarding execution mode explicit and
// fails fast when the built-in relay would start without the minimum upstream
// SMTP settings required to forward mail safely.
func validateMailConfig(mail MailConfig) error {
	switch strings.ToLower(strings.TrimSpace(mail.ForwardingBackend)) {
	case EmailForwardingBackendCloudflare:
		return nil
	case EmailForwardingBackendDatabaseRelay:
		if mail.MaxRecipients < 1 {
			return fmt.Errorf("MAIL_RELAY_MAX_RECIPIENTS must be at least 1")
		}
		if mail.MaxMessageBytes < 1 {
			return fmt.Errorf("MAIL_RELAY_MAX_MESSAGE_BYTES must be at least 1")
		}
		if mail.ReadTimeout <= 0 {
			return fmt.Errorf("MAIL_RELAY_READ_TIMEOUT must be greater than 0")
		}
		if mail.WriteTimeout <= 0 {
			return fmt.Errorf("MAIL_RELAY_WRITE_TIMEOUT must be greater than 0")
		}
		if mail.RelayEnabled {
			if strings.TrimSpace(mail.SMTPAddr) == "" {
				return fmt.Errorf("MAIL_RELAY_SMTP_ADDR is required when MAIL_RELAY_ENABLED=true")
			}
			if strings.TrimSpace(mail.Domain) == "" {
				return fmt.Errorf("MAIL_RELAY_DOMAIN is required when MAIL_RELAY_ENABLED=true")
			}
			if strings.TrimSpace(mail.ForwardHost) == "" {
				return fmt.Errorf("MAIL_RELAY_FORWARD_HOST is required when MAIL_RELAY_ENABLED=true")
			}
			if strings.TrimSpace(mail.ForwardFrom) == "" {
				return fmt.Errorf("MAIL_RELAY_FORWARD_FROM is required when MAIL_RELAY_ENABLED=true")
			}
		}
		return nil
	default:
		return fmt.Errorf("EMAIL_FORWARDING_BACKEND must be one of %s, %s", EmailForwardingBackendCloudflare, EmailForwardingBackendDatabaseRelay)
	}
}
